import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | HiddenMRR',
  description: 'Read the Terms of Service for HiddenMRR, including our payment, refund, and acceptable use policies.',
  alternates: {
    canonical: 'https://www.hiddenmrr.com/terms',
  },
};

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col items-center bg-zinc-950 text-zinc-300 font-sans">
      <div className="w-full max-w-3xl px-6 py-20 sm:py-28">

        {/* Header */}
        <div className="mb-14">
          <p className="text-[10px] font-black uppercase tracking-widest text-primary mb-4">Legal</p>
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tighter text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-zinc-500 text-sm">Last updated: March 17, 2026</p>
        </div>

        <div className="prose prose-sm prose-invert max-w-none space-y-10">

          {/* 1 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using HiddenMRR (&ldquo;the Service&rdquo;), a product of{' '}
              <strong className="text-white">Pintayo Studio</strong> (&ldquo;we&rdquo;,
              &ldquo;us&rdquo;, &ldquo;our&rdquo;), you agree to be bound by these Terms of
              Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.
            </p>
            <p className="mt-3">
              You must be at least <strong className="text-white">18 years of age</strong> to use
              the Service. By using the Service you represent that you meet this requirement.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              HiddenMRR is an AI-powered analysis platform that reads metadata from GitHub
              repositories you authorise and generates business opportunity reports. The Service
              operates on a Bring Your Own Key (BYOK) model — you supply your own OpenAI API key
              to power analysis. We are not an AI provider and bear no responsibility for the
              outputs generated by third-party AI models.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Account Registration</h2>
            <p>
              You must sign in with a GitHub account to use the Service. You are responsible for
              maintaining the confidentiality of your account credentials and for all activity that
              occurs under your account. You must notify us immediately at{' '}
              <a href="mailto:support@pintayo.com" className="text-primary hover:underline">
                support@pintayo.com
              </a>{' '}
              if you suspect unauthorised access.
            </p>
          </section>

          {/* 4 — Payment */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Payment</h2>
            <p>
              Access to paid features requires a one-time payment of{' '}
              <strong className="text-white">USD $29</strong> (or local currency equivalent as
              displayed at checkout), processed by our payment partner{' '}
              <strong className="text-white">Lemon Squeezy</strong>, who acts as Merchant of Record.
              All prices are inclusive of applicable taxes where required by law. Payment is charged
              immediately upon purchase.
            </p>
          </section>

          {/* 5 — Refund Policy (key section) */}
          <section>
            <div className="rounded-2xl border border-primary/20 bg-primary/5 p-6 mb-4">
              <h2 className="text-xl font-bold text-white mb-3">5. Refund &amp; Return Policy</h2>
              <p className="mb-4">
                HiddenMRR provides <strong className="text-white">digital content</strong> that is
                delivered and consumed immediately upon payment. Please read this section carefully
                before purchasing.
              </p>
              <p className="mb-4">
                <strong className="text-white">All sales are final.</strong> By completing your
                purchase and accessing the Service you acknowledge that:
              </p>
              <ol className="list-decimal list-outside ml-5 space-y-3 text-zinc-300">
                <li>
                  The Service constitutes <strong className="text-white">digital content not
                  supplied on a tangible medium</strong> within the meaning of applicable consumer
                  protection legislation, including but not limited to Article&nbsp;16(m) of the EU
                  Consumer Rights Directive 2011/83/EU.
                </li>
                <li>
                  Performance of the Service <strong className="text-white">begins immediately
                  upon purchase</strong>, as access to analysis features is granted at the moment
                  payment is confirmed.
                </li>
                <li>
                  By proceeding with the purchase you <strong className="text-white">expressly
                  consent to immediate performance</strong> and acknowledge that you thereby{' '}
                  <strong className="text-white">waive any right of withdrawal or cancellation
                  </strong> that would otherwise be available under consumer protection law (including
                  EU, UK, and Australian consumer law).
                </li>
                <li>
                  If you have <strong className="text-white">used the Service</strong> — including
                  running at least one repository analysis — you have consumed the digital product
                  and are no longer eligible for a refund under any circumstance.
                </li>
              </ol>
              <p className="mt-4 text-zinc-400">
                If you encounter a technical issue that prevents you from accessing the Service
                after payment, contact us at{' '}
                <a href="mailto:support@pintayo.com" className="text-primary hover:underline">
                  support@pintayo.com
                </a>{' '}
                within <strong className="text-zinc-200">7 days</strong>. We will investigate and,
                at our sole discretion, may issue a goodwill credit or refund where a verified
                technical failure on our part prevented any use of the Service.
              </p>
            </div>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc list-outside ml-5 space-y-2 text-zinc-400">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Attempt to reverse-engineer, decompile, or extract the source code of the Service.</li>
              <li>Resell, sublicense, or redistribute access to the Service without our written permission.</li>
              <li>Submit repositories or content that violates the intellectual property rights of others.</li>
              <li>Abuse the GitHub API or OpenAI API in ways that violate those platforms&rsquo; terms of service.</li>
              <li>Attempt to circumvent payment, access controls, or rate limits.</li>
            </ul>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Your Content &amp; Intellectual Property</h2>
            <p>
              You retain all intellectual property rights in the repositories and code you submit
              for analysis. By using the Service you grant us a limited, temporary licence to read
              repository metadata solely for the purpose of generating your analysis report. We
              claim no ownership over your code or the reports generated from it.
            </p>
            <p className="mt-3">
              Analysis reports are generated for your personal use. You may use, share, and act on
              the reports freely. We do not guarantee the accuracy, completeness, or commercial
              viability of any recommendations.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. BYOK &mdash; Third-Party AI</h2>
            <p>
              Analysis is performed using your own OpenAI API key. You are solely responsible for
              all costs incurred on your OpenAI account, compliance with OpenAI&rsquo;s usage
              policies, and any outputs generated. We are not affiliated with OpenAI and make no
              warranties regarding the performance or output of third-party AI models.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Disclaimers &amp; Limitation of Liability</h2>
            <p className="mb-3">
              The Service is provided <strong className="text-white">&ldquo;as is&rdquo;</strong>{' '}
              and &ldquo;as available&rdquo; without warranties of any kind, express or implied,
              including but not limited to warranties of merchantability, fitness for a particular
              purpose, or non-infringement.
            </p>
            <p className="mb-3">
              We do not warrant that the Service will be uninterrupted, error-free, or free of
              harmful components. Analysis outputs are suggestions only — we make no guarantee of
              business outcomes, revenue, or fitness of any recommendation for your specific
              circumstances.
            </p>
            <p>
              To the maximum extent permitted by applicable law, Pintayo Studio&rsquo;s total
              liability to you for any claim arising from or related to these Terms or the Service
              shall not exceed the amount you paid to us in the{' '}
              <strong className="text-white">12 months preceding the claim</strong>. We are not
              liable for any indirect, incidental, special, consequential, or punitive damages.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Pintayo Studio and its officers, employees,
              and agents from any claims, damages, losses, or expenses (including reasonable legal
              fees) arising out of your use of the Service, violation of these Terms, or
              infringement of any third-party rights.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation
              of these Terms, fraudulent activity, or abuse of the Service, with or without prior
              notice. Upon termination, your right to access the Service ceases immediately.
              Sections 5, 7, 9, 10, and 12 survive termination.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Governing Law &amp; Disputes</h2>
            <p>
              These Terms are governed by and construed in accordance with applicable law. Any
              dispute arising out of or in connection with these Terms shall first be attempted to
              be resolved amicably by contacting us at{' '}
              <a href="mailto:support@pintayo.com" className="text-primary hover:underline">
                support@pintayo.com
              </a>
              . Nothing in these Terms limits your statutory rights as a consumer in your
              jurisdiction.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after
              changes become effective constitutes acceptance of the revised Terms. We will notify
              registered users of material changes via email.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-xl font-bold text-white mb-3">14. Contact</h2>
            <p>
              Questions about these Terms should be directed to Pintayo Studio at{' '}
              <a href="mailto:support@pintayo.com" className="text-primary hover:underline">
                support@pintayo.com
              </a>
              .
            </p>
          </section>

        </div>

        {/* Back link */}
        <div className="mt-16 pt-8 border-t border-white/5">
          <Link href="/" className="text-sm text-zinc-500 hover:text-primary transition-colors">
            ← Back to HiddenMRR
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="w-full border-t border-white/5 py-10 px-6">
        <div className="max-w-3xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-zinc-600 text-[10px] font-bold uppercase tracking-widest">
            © 2026 Pintayo Studio · Built for Builders
          </p>
          <div className="flex gap-8 text-[11px] font-bold uppercase tracking-[0.2em] text-zinc-500">
            <Link href="/privacy" className="hover:text-primary transition-colors">Privacy</Link>
            <Link href="/terms" className="text-primary">Terms</Link>
            <Link href="/support" className="hover:text-primary transition-colors">Support</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}
